version: '2.3' # for runtime

networks:
  cuda-ubuntu20-dev-network:
    driver_opts:
      com.docker.network.bridge.name: "cuda-dev"

services:
  cuda-ubuntu20-env:
    image: cuda:11.1.1-devel-ubuntu20.04
    build:
      context: dockerfiles
      dockerfile: Dockerfile
    runtime: nvidia
    ports:
      - 9000:9000
      - 9001:9001
      - 9002:9002
    volumes:
      - ./:/custom_plugin
      - /tmp/mnist_models:/mnist_models
    shm_size: 1g
    ulimits:
      memlock: -1
      stack: 67108864
    command: bash -c '
        REPOSITORY=./data/server/model-repository &&
        pushd /mnist_models &&
          mkdir -p ./data/server/model-repository &&
            popd &&
        bash -c "while sleep 1000; do :; done"
      '
